name: "Bob's Motor Workshop"
favicon: null
layout_spectrum: 0.007668133592233062
typography_spectrum: 0.18802757188677788
title: "Bob's Motor Workshop"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ddfbfb'
    - '#1a090f'
    - '#1268f1'
    - '#bd8b8e'
    - '#60b0fd'
  brandStrength: 0.9810588655527681
  lightness: 0.3576890896074474
  saturation: 0.2632756596431136
  rhythmicContrast: 0.9493037431966513
purpose: []
